import { Metadata } from "next";
export const metadata: Metadata = {
    title: "IP Analytics",
    description: "Generated by create next app",
  };

export default function RootLayout({
    children,
}:{
    children: React.ReactNode
}) {
    return (
        <html>
            <head>
               <link  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"/>
            </head>
            <body>
                <main>
                  <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
                    <a className="navbar-brand" href="#">IP Analytics</a>
                    <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span className="navbar-toggler-icon"></span>
                    </button>

                    <div className="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul className="navbar-nav mr-auto">
                      <li className="nav-item ">
                        <a className="nav-link" href="/home">Home <span className="sr-only">(current)</span></a>
                      </li>
                      <li className="nav-item">
                        <a className="nav-link" href="/site-history">Site History</a>
                      </li>
                    </ul>
                    </div>
                  </nav>
                  {children}
                </main>
            </body>
        </html>
    );
}